[package]
name = "librrd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
librrd_sys = { package = "librrd-sys", path = "../librrd-sys" }
